version: '3'
services:
  mongo:
    image: mongo
    container_name: wallet-app_mongo_1
    ports:
      - 27017:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all" ]
    volumes:
      - ./docker-cache/mongodb:/data/db
